name: CI workflow
on:
  push:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run : solhint --max-warnings 0 ./contracts/*.sol

      - name: Run unit test cases
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
          GOERLI_PRIVATE_KEY: ${{ secrets.GOERLI_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run : |
          npx hardhat clean
          npx hardhat --max-memory 2048 compile
          npx hardhat test unit_test.js
