name: CI/CD workflow
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run : |
          npm install -g solhint
          solhint --version
          solhint --init
          solhint contracts/**/*.sol

      - name: Run unit test cases
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
          GOERLI_PRIVATE_KEY: ${{ secrets.GOERLI_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run : |
          npx hardhat clean
          npx hardhat --max-memory 2048 compile
          npx hardhat test test/unit_test_v1.js
          npx hardhat test test/unit_test_v2.js

  proxy_deploy:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - uses: actions/checkout@v3

      - name: Install node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy proxy contract
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
          GOERLI_PRIVATE_KEY: ${{ secrets.GOERLI_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          npx hardhat run scripts/deploy.js --network goerli
          export $(xargs < output.txt)

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saved text.file

      - name: Sleep for 30 seconds
        uses: whatnick/wait-action@master
        with:
          time: '30s'

  upgrade_deploy:
    runs-on: ubuntu-latest
    needs: proxy_deploy
    steps:
      - uses: actions/checkout@v3

      - name: Pull new changes
        run: git pull origin main --rebase

      - name: Install node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy proxy contract
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
          GOERLI_PRIVATE_KEY: ${{ secrets.GOERLI_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          npx hardhat run scripts/upgrade.js --network goerli
          export $(xargs < output.txt)

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saved text.file
